name: antigravity
base: core24
version: '2.2.1'
title: Antigravity
summary: Antigravity
icon: snap/gui/icon.png
description: |
  Google Antigravity — Build the new way.

  Your command center to manage multiple local agents in parallel. Group conversations into Projects, operate across multiple workspaces, and automate routine tasks with scheduled messages.
website: https://antigravity.google/
contact: https://antigravity.google/
source-code: https://github.com/canonical/antigravity-snap
issues: https://github.com/canonical/antigravity-snap/issues

grade: stable
confinement: classic

platforms:
  amd64:
  arm64:

apps:
  antigravity:
    command: opt/antigravity/antigravity
    desktop: share/applications/antigravity.desktop

parts:
  antigravity:
    plugin: dump
    source: .
    override-pull: |
      case "$CRAFT_ARCH_BUILD_FOR" in
        amd64)
          URL=https://storage.googleapis.com/antigravity-public/antigravity-hub/2.2.1-5287492581195776/linux-x64/Antigravity.tar.gz
          DIR=Antigravity-x64
          ;;
        arm64)
          URL=https://storage.googleapis.com/antigravity-public/antigravity-hub/2.2.1-5287492581195776/linux-arm/Antigravity.tar.gz
          DIR=Antigravity-arm64
          ;;
        *)
          echo "Unsupported architecture: $CRAFT_ARCH_BUILD_FOR"
          exit 1
          ;;
      esac
      mkdir -p opt share/icons/hicolor/256x256/apps share/applications
      curl -L "$URL" | tar -xz
      mv "$DIR" opt/antigravity
      install -Dm644 "$CRAFT_PROJECT_DIR/snap/icon.png" share/icons/hicolor/256x256/apps/antigravity.png
      install -Dm644 "$CRAFT_PROJECT_DIR/snap/local/antigravity.desktop" share/applications/antigravity.desktop
    build-packages:
      - curl
